services:
  backend:
    build:
      context: ./golang-backend
      dockerfile: Dockerfile
    image: golang-backend
    container_name: golang-backend
    restart: unless-stopped
    working_dir: /app
    ports:
      - "8085:8085"
    volumes:
      - ./golang-backend:/usr/share/nginx/
      - ./golang-backend/config.json:/usr/share/nginx/config.json
    networks:
      - mergeintervals

  nginx:
    build:
      dockerfile: ./docker/nginx/Dockerfile
    container_name: frontend-web
    restart: unless-stopped
    ports:
      - "3010:80"
    volumes:
      - ./docker/nginx/frontend.conf:/etc/nginx/conf.d/default.conf
    networks:
      - mergeintervals
    depends_on:
      - backend

networks:
  mergeintervals:
    driver: bridge
    name: mergeintervals
